Repository blevesearch/bleve, pull requests merged in 2023-08, with the labels that each got.

#1862 MB-57972: Add new layout to dateTimeOptional
  analysis/datetime/flexible/flexible_test.go
  analysis/datetime/optional/optional.go
  index_test.go
Labels: enhancement, backport-to-trinity

#1847 MB-31210: Support Fuzzy MatchPhrase, MultiPhrase and Phrase queries
  search/query/match_phrase.go
  search/query/multi_phrase.go
  search/query/phrase.go
  search/query/query.go
  search/searcher/search_fuzzy.go
  search/searcher/search_phrase.go
  search/searcher/search_phrase_test.go
  search/util.go
Labels: enhancement

#1868 MB-58110: Format dates in search result correctly
  analysis/datetime/flexible/flexible.go
  analysis/datetime/flexible/flexible_test.go
  analysis/type.go
  document/field_datetime.go
  go.mod
  go.sum
  http/doc_get.go
  index/scorch/scorch_test.go
  index/upsidedown/dump_test.go
  index/upsidedown/upsidedown_test.go
  index_impl.go
  mapping/document.go
  mapping/field.go
  search.go
  search/query/date_range.go
  search/search.go
Labels: bug, backport-to-trinity

#1864 MB-54131: Geoshape query decode optimization
  go.mod
  go.sum
  index_impl.go
  search/searcher/search_geoshape.go
  search/util.go
Labels: backport-to-trinity
